### ISSUE TITLE
research hall effect sensors

### ISSUE THREAD

**Issue by bhowiebkr** [bhowiebkr/open-joystick#2]

**Comment by bhowiebkr** [comment]
decided to go with a complete motor driver solution by ODrive for 2 of the axis. These axis will be encoder based. Twist axis will use hall effect sensors

**Comment by thepopejp** [comment]
Hey - I'm actually in the process of building out a parts list and modifying Olukelo's design as well. I'd be interested to hear why you made the choices you have. If you're on discord let's connect so we can see if we couldn't work together.
